Traceback (most recent call last):
  File "/home/maxhchen/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/maxhchen/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 2398, in <module>
    from tensorflow.python.util import deprecation
  File "/home/maxhchen/.local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 25, in <module>
    from tensorflow.python.platform import tf_logging as logging
  File "/home/maxhchen/.local/lib/python3.7/site-packages/tensorflow/python/platform/tf_logging.py", line 36, in <module>
    import six
ModuleNotFoundError: No module named 'six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 4, in <module>
    import tensorflow as tf
  File "/home/maxhchen/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/maxhchen/.local/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/maxhchen/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/maxhchen/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/maxhchen/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 2398, in <module>
    from tensorflow.python.util import deprecation
  File "/home/maxhchen/.local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 25, in <module>
    from tensorflow.python.platform import tf_logging as logging
  File "/home/maxhchen/.local/lib/python3.7/site-packages/tensorflow/python/platform/tf_logging.py", line 36, in <module>
    import six
ModuleNotFoundError: No module named 'six'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
2021-05-11 10:45:51.861611: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 10:45:51.861654: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 221, in main
    tf.logging.set_verbosity(tf.logging.ERROR)
AttributeError: module 'tensorflow' has no attribute 'logging'
2021-05-11 10:46:26.095454: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 10:46:26.095495: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 221, in main
    tf.logging.set_verbosity(tf.logging.ERROR)
AttributeError: module 'tensorflow' has no attribute 'logging'
2021-05-11 10:48:01.867609: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 10:48:01.867651: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 127, in train_fn
    config = tf.ConfigProto()
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
2021-05-11 10:48:17.726887: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 10:48:17.726929: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 127, in train_fn
    config = tf.ConfigProto()
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
2021-05-11 10:49:11.265751: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 10:49:11.265796: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 129, in train_fn
    sess = tf.Session(config=config)
AttributeError: module 'tensorflow' has no attribute 'Session'
2021-05-11 10:50:06.663637: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 10:50:06.663687: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 10:50:10.292171: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 10:50:10.293121: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 10:50:10.293666: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 10:50:10.293704: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 10:50:10.293759: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 61, in learn
    set_global_seeds(seed)
  File "/home/maxhchen/.local/lib/python3.7/site-packages/baselines/common/misc_util.py", line 58, in set_global_seeds
    tf.set_random_seed(myseed)
AttributeError: module 'tensorflow' has no attribute 'set_random_seed'
2021-05-11 10:55:44.870534: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 10:55:44.870579: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 10:55:48.533615: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 10:55:48.534380: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 10:55:48.534956: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 10:55:48.534985: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 10:55:48.535016: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 77, in learn
    set_global_seeds(seed)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 29, in set_global_seeds
    tf.compat.v1.set_random_seed(myself)
NameError: name 'myself' is not defined
2021-05-11 10:56:21.199905: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 10:56:21.199946: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 10:56:24.808714: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 10:56:24.809798: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 10:56:24.810220: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 10:56:24.810256: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 10:56:24.810282: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 77, in learn
    set_global_seeds(seed)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 33, in set_global_seeds
    random.seed(myseed)
NameError: name 'random' is not defined
2021-05-11 10:57:02.867925: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 10:57:02.867967: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 10:57:06.518232: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 10:57:06.519198: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 10:57:06.519674: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 10:57:06.519709: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 10:57:06.519761: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 27, in __init__
    self.sess = sess = get_session()
  File "/home/maxhchen/.local/lib/python3.7/site-packages/baselines/common/tf_util.py", line 53, in get_session
    sess = tf.get_default_session()
AttributeError: module 'tensorflow' has no attribute 'get_default_session'
2021-05-11 11:01:18.756046: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:01:18.756087: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:01:22.386509: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:01:22.387587: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:01:22.387928: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:01:22.387956: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:01:22.387993: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 39, in __init__
    with tf.variable_scope('ppo2_model', reuse=tf.AUTO_REUSE):
AttributeError: module 'tensorflow' has no attribute 'variable_scope'
2021-05-11 11:01:53.126774: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:01:53.126848: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:01:56.738627: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:01:56.739468: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:01:56.739814: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:01:56.739842: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:01:56.739865: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 39, in __init__
    with tf.compat.v1.variable_scope('ppo2_model', reuse=tf.AUTO_REUSE):
AttributeError: module 'tensorflow' has no attribute 'AUTO_REUSE'
2021-05-11 11:02:05.663215: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:02:05.663263: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:02:09.247843: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:02:09.249034: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:02:09.249403: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:02:09.249443: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:02:09.249486: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 39, in __init__
    with tf.compat.v1.variable_scope('ppo2_model', reuse=tf.AUTO_REUSE):
AttributeError: module 'tensorflow' has no attribute 'AUTO_REUSE'
2021-05-11 11:02:28.676272: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:02:28.676331: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:02:32.310423: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:02:32.311457: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:02:32.312026: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:02:32.312055: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:02:32.312086: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 42, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 122, in policy_fn
    X = observ_placeholder if observ_placeholder is not None else observation_placeholder(ob_space, batch_size=nbatch)
  File "/home/maxhchen/.local/lib/python3.7/site-packages/baselines/common/input.py", line 31, in observation_placeholder
    return tf.placeholder(shape=(batch_size,) + ob_space.shape, dtype=dtype, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'
2021-05-11 11:06:34.904391: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:06:34.904435: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:06:38.524746: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:06:38.525742: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:06:38.526260: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:06:38.526294: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:06:38.526322: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 61, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 122, in policy_fn
    X = observ_placeholder if observ_placeholder is not None else observation_placeholder(ob_space, batch_size=nbatch)
  File "/home/maxhchen/.local/lib/python3.7/site-packages/baselines/common/input.py", line 31, in observation_placeholder
    return tf.placeholder(shape=(batch_size,) + ob_space.shape, dtype=dtype, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'
2021-05-11 11:07:14.945125: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:07:14.945170: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:07:18.559594: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:07:18.560607: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:07:18.561091: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:07:18.561123: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:07:18.561149: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 61, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 122, in policy_fn
    X = observ_placeholder if observ_placeholder is not None else observation_placeholder(ob_space, batch_size=nbatch)
  File "/home/maxhchen/.local/lib/python3.7/site-packages/baselines/common/input.py", line 31, in observation_placeholder
    return tf.placeholder(shape=(batch_size,) + ob_space.shape, dtype=dtype, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'
2021-05-11 11:13:48.925609: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:13:48.925649: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:13:52.554238: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:13:52.555164: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:13:52.555730: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:13:52.555766: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:13:52.555872: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 42, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 144, in policy_fn
    X = observ_placeholder if observ_placeholder is not None else observation_placeholder(ob_space, batch_size=nbatch)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 27, in observation_placeholder
    assert isinstance(ob_space, Discrete) or isinstance(ob_space, Box) or isinstance(ob_space, MultiDiscrete), \
NameError: name 'Discrete' is not defined
2021-05-11 11:15:42.725545: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:15:42.725585: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:15:46.365232: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:15:46.366261: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:15:46.366742: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:15:46.366778: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:15:46.366807: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 42, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 145, in policy_fn
    X = observ_placeholder if observ_placeholder is not None else observation_placeholder(ob_space, batch_size=nbatch)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 32, in observation_placeholder
    if dtype == np.int8:
NameError: name 'np' is not defined
2021-05-11 11:16:12.166289: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:16:12.166337: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:16:15.812115: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:16:15.813142: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:16:15.813608: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:16:15.813637: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:16:15.813662: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 42, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 156, in policy_fn
    encoded_x = encode_observation(ob_space, encoded_x)
  File "/home/maxhchen/.local/lib/python3.7/site-packages/baselines/common/input.py", line 57, in encode_observation
    return tf.to_float(placeholder)
AttributeError: module 'tensorflow' has no attribute 'to_float'
2021-05-11 11:19:35.048392: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:19:35.048434: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:19:38.682863: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:19:38.683960: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:19:38.684546: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:19:38.684588: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:19:38.684663: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 42, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 176, in policy_fn
    with tf.variable_scope('pi', reuse=tf.AUTO_REUSE):
AttributeError: module 'tensorflow' has no attribute 'variable_scope'
2021-05-11 11:20:48.711502: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:20:48.711544: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:20:52.368019: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:20:52.369329: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:20:52.369804: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:20:52.369838: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:20:52.369864: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 42, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 176, in policy_fn
    with tf.compat.v1.ariable_scope('pi', reuse=tf.compat.v1.AUTO_REUSE):
AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'ariable_scope'
2021-05-11 11:21:01.672940: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:21:01.672990: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:21:05.346127: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:21:05.347004: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:21:05.347384: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:21:05.347411: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:21:05.347457: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 42, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 176, in policy_fn
    with tf.compat.v1.ariable_scope('pi', reuse=tf.compat.v1.AUTO_REUSE):
AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'ariable_scope'
2021-05-11 11:21:17.153545: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:21:17.153585: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:21:20.815936: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:21:20.817435: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:21:20.817725: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:21:20.817751: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:21:20.817783: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 42, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 176, in policy_fn
    with tf.compat.v1.Variable_scope('pi', reuse=tf.compat.v1.AUTO_REUSE):
AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'Variable_scope'
2021-05-11 11:21:43.923983: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 11:21:43.924042: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using none Scheduler for Entropy Decay
Saving to dir: model-15-baseline-noise-1
Using high entropy? False
Constant Entropy Coeff
Logging to model-15-baseline-noise-1
creating environment
creating tf session
2021-05-11 11:21:47.560772: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 11:21:47.561484: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 11:21:47.561806: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 11:21:47.561834: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 11:21:47.561859: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-1): /proc/driver/nvidia/version does not exist
training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 250, in <module>
    main()
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 240, in main
    comm=comm,
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 160, in train_fn
    tensorboard_log = "./tensorboard_logs/"
  File "/home/maxhchen/CS182_RL_Project/train_procgen/ppo_decay2.py", line 124, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_model.py", line 42, in __init__
    act_model = policy(nbatch_act, 1, sess)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/alt_policies.py", line 177, in policy_fn
    policy_latent = policy_network(encoded_x)
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 132, in <lambda>
    conv_fn = lambda x: build_impala_cnn(x, depths=[16,32,32], emb_size=256)
  File "/home/maxhchen/.local/lib/python3.7/site-packages/baselines/common/models.py", line 65, in build_impala_cnn
    out = conv_sequence(out, depth)
  File "/home/maxhchen/.local/lib/python3.7/site-packages/baselines/common/models.py", line 56, in conv_sequence
    out = conv_layer(inputs, depth)
  File "/home/maxhchen/.local/lib/python3.7/site-packages/baselines/common/models.py", line 43, in conv_layer
    return tf.layers.conv2d(out, depth, 3, padding='same', name='layer_' + get_layer_num_str())
AttributeError: module 'tensorflow' has no attribute 'layers'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/maxhchen/CS182_RL_Project/train_procgen/train.py", line 52
    nonlocal layer_num
    ^
SyntaxError: no binding for nonlocal 'layer_num' found
